#include "se/native_brain_engine.hpp"
#include "se/world.hpp"
#include "se/event_scheduler.hpp"
#include <algorithm>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/numpy.h>
namespace py=pybind11;using namespace se;
PYBIND11_MODULE(_native_brain,m){
  py::class_<RuntimeEvent>(m,"RuntimeEvent").def(py::init([](double t,std::uint64_t id,RuntimeEventType type,std::uint64_t payload){return RuntimeEvent{t,id,type,payload};})).def_readonly("time",&RuntimeEvent::time).def_readonly("id",&RuntimeEvent::id).def_readonly("type",&RuntimeEvent::type).def_readonly("payload",&RuntimeEvent::payload);
  py::enum_<RuntimeEventType>(m,"RuntimeEventType").value("WORLD_ACTION_COMPLETE",RuntimeEventType::WorldActionComplete).value("WORLD_SPAWN",RuntimeEventType::WorldSpawn).value("SENSORY_CHANGE",RuntimeEventType::SensoryChange).value("COGNITION_WAKE",RuntimeEventType::CognitionWake).value("COGNITION_CONTINUE",RuntimeEventType::CognitionContinue).value("MEMORY_TIMER",RuntimeEventType::MemoryTimer).value("RELATION_TIMER",RuntimeEventType::RelationTimer).value("MAINTENANCE",RuntimeEventType::Maintenance).value("EXTERNAL_INPUT",RuntimeEventType::ExternalInput);
  py::class_<EventScheduler>(m,"EventScheduler").def(py::init<>()).def("schedule",&EventScheduler::schedule,py::arg("time"),py::arg("event_type"),py::arg("payload")=0).def("pop_ready",&EventScheduler::pop_ready).def("snapshot",&EventScheduler::snapshot).def("restore",&EventScheduler::restore).def_property_readonly("now",&EventScheduler::now).def_property_readonly("next_id",&EventScheduler::next_id).def_property_readonly("size",&EventScheduler::size);
  py::class_<World>(m,"WorldRuntime").def(py::init<int,int,int>(),py::arg("width")=30,py::arg("height")=30,py::arg("radius")=4)
    .def("initialize",[](World&w,int x,int y,const std::string&o,const std::vector<std::pair<int,int>>&objects){w.initialize({x,y,o.empty()?'N':o[0]},objects);})
    .def("initialize_multi",[](World&w,const std::vector<std::tuple<std::uint32_t,int,int,std::string,std::uint16_t>>&bodies,const std::vector<std::tuple<std::uint32_t,int,int,int>>&objects){std::vector<Body>bs;std::vector<Object>os;for(auto&[id,x,y,o,appearance]:bodies)bs.push_back({x,y,o.empty()?'N':o[0],0,appearance,id});for(auto&[id,x,y,state]:objects)os.push_back({id,x,y,state});w.initialize_multi(std::move(bs),std::move(os));})
    .def("restore",[](World&w,const std::vector<std::tuple<std::uint32_t,int,int,std::string,std::uint16_t>>&bodies,const std::vector<std::tuple<std::uint32_t,int,int,int>>&objects,const std::vector<std::tuple<std::uint32_t,std::uint32_t,int,int,int>>&held,const std::vector<double>&resistance,std::uint64_t tick,std::optional<std::uint64_t>next,std::uint32_t next_id,std::uint32_t cursor,std::uint64_t conflicts,const std::vector<std::uint64_t>&wins,double time,std::uint64_t sequence,std::uint32_t max_objects){std::vector<Body>bs;std::vector<Object>os;std::vector<std::pair<std::uint32_t,Object>>hs;for(auto&[id,x,y,o,appearance]:bodies)bs.push_back({x,y,o.empty()?'N':o[0],0,appearance,id});for(auto&[id,x,y,state]:objects)os.push_back({id,x,y,state});for(auto&[body,id,x,y,state]:held)hs.push_back({body,{id,x,y,state}});w.restore(std::move(bs),std::move(os),std::move(hs),resistance,tick,next,next_id,cursor,conflicts,wins,time,sequence,max_objects);})
    .def("set_body_state",[](World&w,std::uint32_t id,int x,int y,const std::string&o){w.set_body_state(id,x,y,o.empty()?'N':o[0]);})
    .def("configure_spawning",&World::configure_spawning).def("world_tick",[](World&w,py::object position,py::object next){std::optional<std::pair<int,int>>p;if(!position.is_none())p=position.cast<std::pair<int,int>>();std::optional<std::uint64_t>n;if(!next.is_none())n=next.cast<std::uint64_t>();return w.world_tick(p,n);})
    .def("apply_spawn_event",[](World&w,py::object position,double time,std::uint64_t event){std::optional<std::pair<int,int>>p;if(!position.is_none())p=position.cast<std::pair<int,int>>();auto result=w.apply_spawn_event(p,time,event);return result?py::cast(*result):py::none();})
    .def("apply",[](World&w,int action,std::uint32_t body_id){return (int)w.apply((ActionType)action,body_id);},py::arg("action"),py::arg("body_id")=0)
    .def("resolve_intents",[](World&w,const std::vector<std::uint32_t>&ids,const std::vector<std::uint8_t>&actions){auto rows=w.resolve_intents(ids,actions);std::vector<int>out;for(auto value:rows)out.push_back((int)value);return out;})
    .def("apply_intent",[](World&w,int action,double issued,std::uint64_t event){return (int)w.apply_intent((ActionType)action,issued,event);})
    .def("advance_world_time",&World::advance_world_time).def("time_state",[](const World&w){return py::make_tuple(w.world_time(),w.event_sequence());})
    .def("latest_render_snapshot",[](const World&w){auto s=w.latest_render_snapshot();py::list bodies,objects,held;for(auto const&b:s.bodies)bodies.append(py::make_tuple(b.id,b.x,b.y,std::string(1,b.orientation),b.appearance,b.held_object_id));for(auto const&o:s.objects)objects.append(py::make_tuple(o.id,o.x,o.y,o.state));for(auto const&h:s.held_objects)held.append(py::make_tuple(h.owner_body_id,h.object_id,h.state));return py::make_tuple(s.world_time,s.event_sequence,s.world_width,s.world_height,bodies,objects,held);})
    .def("state",[](const World&w){py::list objects;for(auto&o:w.objects())objects.append(py::make_tuple(o.id,o.x,o.y,o.state));auto&b=w.body();return py::make_tuple(b.x,b.y,std::string(1,b.orientation),b.held_object_id,objects,w.resistance());})
    .def("full_state",[](const World&w){py::list bodies,objects,held;for(auto&b:w.bodies())bodies.append(py::make_tuple(b.id,b.x,b.y,std::string(1,b.orientation),b.held_object_id,b.appearance));auto sorted=w.objects();std::sort(sorted.begin(),sorted.end(),[](auto&a,auto&b){return a.id<b.id;});for(auto&o:sorted)objects.append(py::make_tuple(o.id,o.x,o.y,o.state));for(std::size_t i=0;i<w.held_objects().size();++i)if(w.held_objects()[i]){auto&o=*w.held_objects()[i];held.append(py::make_tuple((std::uint32_t)i,o.id,o.x,o.y,o.state));}return py::make_tuple(bodies,objects,held,w.world_tick_count(),w.next_spawn_tick(),w.next_object_id(),w.conflict_cursor(),w.conflict_count(),w.fairness_wins());})
    .def("resistances",&World::resistances)
    .def("perceive",[](const World&w,std::uint64_t tick,std::uint32_t body_id){auto f=w.perceive(tick,body_id);py::list cells;for(auto&c:f.cells)cells.append(py::make_tuple(c.dx,c.dy,c.occupied,c.state,c.boundary,c.self,c.appearance));return py::make_tuple(cells,py::make_tuple(f.body.up,f.body.down,f.body.left,f.body.right,f.body.holding,f.body.resistance));},py::arg("tick"),py::arg("body_id")=0);
  py::class_<EvidenceConfig>(m,"EvidenceConfig").def(py::init<>()).def_readwrite("minimum_support",&EvidenceConfig::minimum_support).def_readwrite("minimum_lift",&EvidenceConfig::minimum_lift).def_readwrite("confidence_k",&EvidenceConfig::confidence_k).def_readwrite("consolidated_support",&EvidenceConfig::consolidated_support).def_readwrite("consolidated_confidence",&EvidenceConfig::consolidated_confidence);
  py::class_<NativeBrainEngine>(m,"NativeBrainEngine")
    .def(py::init<std::size_t>(),py::arg("evidence_window")=512).def("add_cognit",&NativeBrainEngine::add_cognit,py::arg("activity")=0,py::arg("threshold")=.25,py::arg("confidence")=.5)
    .def("add_cognits",&NativeBrainEngine::add_cognits,py::arg("count"),py::arg("activity")=0,py::arg("threshold")=.25,py::arg("confidence")=.5)
    .def("set_activity",&NativeBrainEngine::set_activity)
    .def("transition_history",&NativeBrainEngine::transition_history).def("restore_transition_history",&NativeBrainEngine::restore_transition_history).def("homeostasis_runtime_state",&NativeBrainEngine::homeostasis_runtime_state).def("restore_homeostasis_runtime_state",&NativeBrainEngine::restore_homeostasis_runtime_state).def("dirty_relation_state",&NativeBrainEngine::dirty_relation_state).def("restore_dirty_relation_state",&NativeBrainEngine::restore_dirty_relation_state)
    .def("remove_cognit",&NativeBrainEngine::remove_cognit)
    .def("cognit_alive",&NativeBrainEngine::cognit_alive)
    .def_property_readonly("state_revision",&NativeBrainEngine::state_revision)
    .def_property_readonly("live_cognit_count",&NativeBrainEngine::live_cognit_count)
    .def("set_refractory",&NativeBrainEngine::set_refractory)
    .def("receive",&NativeBrainEngine::receive)
    .def("receive_batch",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids,const std::vector<double>&energies,std::uint64_t tick,bool wave_step,double attenuation,std::uint16_t refractory_steps){py::gil_scoped_release release;return e.receive_batch(ids,energies,tick,wave_step,attenuation,refractory_steps);})
    .def("add_relation",[](NativeBrainEngine&e,std::uint32_t s,std::uint32_t t,int type,std::uint32_t action,double strength,double confidence,double probability){auto h=e.add_relation(s,t,(RelationType)type,action,strength,confidence,probability);return py::make_tuple(h.page,h.slot,h.generation);},py::arg("source"),py::arg("target"),py::arg("relation_type"),py::arg("action")=0,py::arg("strength")=.2,py::arg("confidence")=.3,py::arg("probability")=0.)
    .def("remove_relation",[](NativeBrainEngine&e,const std::tuple<std::uint32_t,std::uint32_t,std::uint32_t>&h){return e.remove_relation({std::get<0>(h),std::get<1>(h),std::get<2>(h)});}).def("relation_handle_valid",[](NativeBrainEngine&e,const std::tuple<std::uint32_t,std::uint32_t,std::uint32_t>&h){return e.relation_handle_valid({std::get<0>(h),std::get<1>(h),std::get<2>(h)});})
    .def("outgoing",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&sources){auto rows=e.outgoing(sources);py::list out;for(auto&[h,r]:rows)out.append(py::make_tuple(r.source,r.target,r.type,r.action,r.strength,r.confidence,r.prediction,r.support,r.lift,r.last_evidence_world_tick,r.status,r.contradiction,r.usefulness,r.confirmations,r.last_used_cognitive_tick,py::make_tuple(h.page,h.slot,h.generation)));return out;})
    .def("outgoing_targets",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&sources){py::gil_scoped_release release;return e.outgoing_targets(sources);})
    .def("relation_state",[](NativeBrainEngine&e,std::uint32_t source,const std::tuple<std::uint32_t,std::uint32_t,std::uint32_t>&raw){RelationHandle h{std::get<0>(raw),std::get<1>(raw),std::get<2>(raw)};auto r=e.relation_state(source,h);return py::make_tuple(r.source,r.target,r.type,r.action,r.strength,r.confidence,r.prediction,r.support,r.lift,r.last_evidence_world_tick,r.status,r.contradiction,r.usefulness,r.confirmations,r.last_used_cognitive_tick,raw);})
    .def("update_relation",[](NativeBrainEngine&e,const std::tuple<std::uint32_t,std::uint32_t,std::uint32_t>&h,const std::tuple<double,double,double,std::uint32_t,double,std::uint64_t,std::uint8_t,double,double,std::uint32_t,std::uint64_t>&v){PersistedRelation r;r.strength=std::get<0>(v);r.confidence=std::get<1>(v);r.prediction=std::get<2>(v);r.support=std::get<3>(v);r.lift=std::get<4>(v);r.last_evidence_world_tick=std::get<5>(v);r.status=std::get<6>(v);r.contradiction=std::get<7>(v);r.usefulness=std::get<8>(v);r.confirmations=std::get<9>(v);r.last_used_cognitive_tick=std::get<10>(v);e.update_relation({std::get<0>(h),std::get<1>(h),std::get<2>(h)},r);})
    .def("predict",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&active,int action){py::gil_scoped_release release;return e.predict(active,(std::uint8_t)action);})
    .def("predict_compact",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&active,int action){std::vector<std::pair<std::uint32_t,double>>rows;{py::gil_scoped_release release;rows=e.predict(active,(std::uint8_t)action);}py::array_t<std::uint32_t>ids(rows.size());py::array_t<double>values(rows.size());auto*i=ids.mutable_data();auto*v=values.mutable_data();for(std::size_t n=0;n<rows.size();++n){i[n]=rows[n].first;v[n]=rows[n].second;}return py::make_tuple(std::move(ids),std::move(values));})
    .def("predict_actions_batch",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&active,const std::vector<std::uint8_t>&actions){py::gil_scoped_release release;return e.predict_actions_batch(active,actions);})
    .def("predict_actions_batch_at",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&active,const std::vector<std::uint8_t>&actions,std::uint64_t tick,double decay){py::gil_scoped_release release;return e.predict_actions_batch_at(active,actions,tick,decay);})
    .def("action_effects",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&active,int action,double floor){py::gil_scoped_release release;return e.action_effects(active,(std::uint8_t)action,floor);})
    .def("action_effects_batch",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&active,const std::vector<std::uint8_t>&actions,double floor){py::gil_scoped_release release;return e.action_effects_batch(active,actions,floor);})
    .def("planner_transition_batch",[](NativeBrainEngine&e,const std::vector<std::vector<std::uint32_t>>&states,const std::vector<std::uint8_t>&actions,std::uint64_t tick,double decay,double floor){std::vector<PlannerTransition>rows;{py::gil_scoped_release release;rows=e.planner_transition_batch(states,actions,tick,decay,floor);}py::list out;for(auto&row:rows)out.append(py::make_tuple(row.predictions,row.effects));return out;})
    .def("propagate",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&seeds,std::uint64_t tick){py::gil_scoped_release release;auto r=e.propagate(seeds,tick);return std::make_tuple(r.active,r.energy,r.steps,r.transmitted_energy);})
    .def("cognit_state",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids){return e.cognit_state(ids);})
    .def("cognit_state_full",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids){return e.cognit_state_full(ids);})
    .def("cognit_state_masked",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids,std::uint16_t mask){return e.cognit_state_masked(ids,mask);})
    .def("set_cognit_states",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids,const std::vector<double>&values){e.set_cognit_states(ids,values);})
    .def("set_cognit_fields",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids,const std::vector<std::uint8_t>&fields,const std::vector<double>&values){e.set_cognit_fields(ids,fields,values);})
    .def("homeostatic_step",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&active,double trace_decay,double learning_rate,double threshold_min,double threshold_max,double activity_decay,double utility_decay){py::gil_scoped_release release;e.homeostatic_step(active,trace_decay,learning_rate,threshold_min,threshold_max,activity_decay,utility_decay);})
    .def("begin_continuous_time",&NativeBrainEngine::begin_continuous_time)
    .def("materialize_cognits_at",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids,double now){py::gil_scoped_release release;e.materialize_cognits_at(ids,now);})
    .def("cognit_elapsed_times",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&ids){return e.cognit_elapsed_times(ids);})
    .def("continuous_time_state",&NativeBrainEngine::continuous_time_state)
    .def("restore_continuous_time_state",&NativeBrainEngine::restore_continuous_time_state,py::arg("enabled"),py::arg("epoch"),py::arg("now"),py::arg("last_touch"),py::arg("last_active"),py::arg("latent_threshold"),py::arg("work")=0)
    .def("continuous_relation_time_state",&NativeBrainEngine::continuous_relation_time_state)
    .def("restore_continuous_relation_time_state",&NativeBrainEngine::restore_continuous_relation_time_state,py::arg("rows"),py::arg("work")=0)
    .def("update_transition_evidence",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&before,int action,const std::vector<std::uint32_t>&after){py::gil_scoped_release release;e.update_transition_evidence(before,(std::uint8_t)action,after);})
    .def("materialize_relations",[](NativeBrainEngine&e,const EvidenceConfig&c,std::uint64_t tick){py::gil_scoped_release release;auto rows=e.materialize_relations(c,tick);std::vector<std::tuple<std::uint32_t,std::uint32_t,std::uint8_t,std::uint32_t,double,double,double>>out;for(auto&r:rows)out.emplace_back(r.source,r.target,r.action,r.support,r.probability,r.confidence,r.lift);return out;})
    .def("materialize_current",[](NativeBrainEngine&e,const EvidenceConfig&c,std::uint64_t tick,const std::vector<std::uint32_t>&before,int action,const std::vector<std::uint32_t>&after,std::uint32_t max_new,std::uint32_t max_relations,double decay){std::vector<MaterializedRelation>rows;{py::gil_scoped_release release;rows=e.materialize_current(c,tick,before,(std::uint8_t)action,after,max_new,max_relations,decay);}std::vector<std::tuple<std::uint32_t,std::uint32_t,std::uint8_t,std::uint32_t,double,double,double>>out;for(auto&r:rows)out.emplace_back(r.source,r.target,r.action,r.support,r.probability,r.confidence,r.lift);return out;})
    .def("clear_transition_evidence",&NativeBrainEngine::clear_transition_evidence).def("set_evidence_window",&NativeBrainEngine::set_evidence_window).def_property_readonly("evidence_stats",&NativeBrainEngine::evidence_stats)
    .def("transition_metrics",&NativeBrainEngine::transition_metrics)
    .def("action_trials",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&sources,const std::vector<std::uint8_t>&actions){return e.action_trials(sources,actions);})
    .def("update_outcomes",[](NativeBrainEngine&e,const std::vector<std::uint32_t>&before,const std::vector<std::uint32_t>&current,int action,std::uint64_t tick,double confirmation,double contradiction,double utility,double consolidated){py::gil_scoped_release release;e.update_outcomes(before,current,action,tick,confirmation,contradiction,utility,consolidated);})
    .def("lifecycle_step",&NativeBrainEngine::lifecycle_step)
    .def("save_graph",&NativeBrainEngine::save_graph).def("load_graph",&NativeBrainEngine::load_graph)
    .def_property_readonly("cognit_count",&NativeBrainEngine::cognit_count).def_property_readonly("relation_count",&NativeBrainEngine::relation_count).def_property_readonly("provisional_count",&NativeBrainEngine::provisional_count).def_property_readonly("consolidated_count",&NativeBrainEngine::consolidated_count).def_property_readonly("logical_bytes",&NativeBrainEngine::logical_bytes).def_property_readonly("reserved_bytes",&NativeBrainEngine::reserved_bytes).def_property_readonly_static("provisional_relation_bytes",[](py::object){return NativeBrainEngine::provisional_relation_bytes();}).def_property_readonly_static("consolidated_relation_bytes",[](py::object){return NativeBrainEngine::consolidated_relation_bytes();});
  m.attr("RELATION_ASSOCIATIVE")=(int)RelationType::Associative;m.attr("RELATION_SEQUENTIAL")=(int)RelationType::Sequential;m.attr("RELATION_SELF_ACTION")=(int)RelationType::SelfAction;
}
