#include "se/neurodynamic_substrate.hpp"
#include <cmath>
#include <stdexcept>
#include <algorithm>
#include <array>
namespace se {
NeurodynamicSubstrate::NeurodynamicSubstrate(double tm,double ta,double rp,double reset,double inc,std::uint64_t guard):tau_membrane_(tm),tau_adaptation_(ta),refractory_period_(rp),reset_potential_(reset),adaptation_increment_(inc),event_guard_(guard){if(!(tm>0&&ta>0&&rp>=0&&std::isfinite(tm)&&std::isfinite(ta)&&std::isfinite(rp)&&std::isfinite(reset)&&std::isfinite(inc)))throw std::invalid_argument("invalid innate neuro physiology");}
void NeurodynamicSubstrate::validate_time(double t)const{if(!std::isfinite(t)||t<now_)throw std::invalid_argument("neural time must be finite and monotonic");}
std::uint32_t NeurodynamicSubstrate::add_micro_kappa(double threshold){if(!std::isfinite(threshold))throw std::invalid_argument("invalid threshold");auto id=(std::uint32_t)potential_.size();potential_.push_back(reset_potential_);base_threshold_.push_back(threshold);last_update_.push_back(now_);refractory_until_.push_back(-INFINITY);adaptation_.push_back(0.);last_spike_.push_back(-INFINITY);spike_count_.push_back(0);outgoing_.emplace_back();return id;}
std::uint32_t NeurodynamicSubstrate::add_micro_rho(std::uint32_t s,std::uint32_t t,double w,double d,MicroPolarity p){if(s>=potential_.size()||t>=potential_.size()||!std::isfinite(w)||!std::isfinite(d)||w<0||d<=0)throw std::invalid_argument("invalid micro rho");auto id=(std::uint32_t)source_.size();source_.push_back(s);target_.push_back(t);weight_.push_back(w);delay_.push_back(d);polarity_.push_back((std::uint8_t)p);outgoing_[s].push_back(id);return id;}
void NeurodynamicSubstrate::schedule(std::uint32_t target,double amplitude,double time){queue_.push({time,next_sequence_++,target,amplitude});telemetry_.max_queue_depth=std::max<std::uint64_t>(telemetry_.max_queue_depth,queue_.size());}
void NeurodynamicSubstrate::inject(std::uint32_t target,double amplitude,double time){validate_time(time);if(target>=potential_.size()||!std::isfinite(amplitude))throw std::invalid_argument("invalid neural injection");schedule(target,amplitude,time);}
void NeurodynamicSubstrate::touch(std::uint32_t id,double time){auto dt=time-last_update_[id];if(dt<0)throw std::invalid_argument("neural time travel");if(dt){potential_[id]*=std::exp(-dt/tau_membrane_);adaptation_[id]*=std::exp(-dt/tau_adaptation_);last_update_[id]=time;}}
void NeurodynamicSubstrate::deliver(double time,const std::vector<NeuralEvent>&events){std::map<std::uint32_t,std::vector<double>> groups;for(auto const&e:events)groups[e.target].push_back(e.amplitude);for(auto&[id,amplitudes]:groups){std::sort(amplitudes.begin(),amplitudes.end());double sum{};for(auto amplitude:amplitudes)sum+=amplitude;touch(id,time);if(time<refractory_until_[id]){telemetry_.refractory_discards+=amplitudes.size();potential_[id]=reset_potential_;continue;}potential_[id]+=sum;if(potential_[id]>=base_threshold_[id]+adaptation_[id]){++spike_count_[id];last_spike_[id]=time;potential_[id]=reset_potential_;adaptation_[id]+=adaptation_increment_;refractory_until_[id]=time+refractory_period_;++telemetry_.total_spikes;for(auto rho:outgoing_[id])schedule(target_[rho],polarity_[rho]==(std::uint8_t)MicroPolarity::Excitatory?weight_[rho]:-weight_[rho],time+delay_[rho]);}}}
void NeurodynamicSubstrate::advance_to(double time){validate_time(time);telemetry_.last_advance_events_processed=0;while(!queue_.empty()&&queue_.top().time<=time){auto stamp=queue_.top().time;std::vector<NeuralEvent>batch;while(!queue_.empty()&&queue_.top().time==stamp){batch.push_back(queue_.top());queue_.pop();if(++telemetry_.last_advance_events_processed>event_guard_)throw std::runtime_error("neural event safety guard exceeded");}telemetry_.total_events_processed+=batch.size();deliver(stamp,batch);}now_=time;}
std::vector<std::array<double,7>> NeurodynamicSubstrate::states(const std::vector<std::uint32_t>&ids)const{std::vector<std::array<double,7>>out;out.reserve(ids.size());for(auto id:ids){if(id>=potential_.size())throw std::out_of_range("invalid micro kappa");out.push_back({potential_[id],base_threshold_[id],last_update_[id],refractory_until_[id],adaptation_[id],last_spike_[id],double(spike_count_[id])});}return out;}
NeuroSnapshot NeurodynamicSubstrate::snapshot()const{NeuroSnapshot s;s.now=now_;s.next_sequence=next_sequence_;s.potential=potential_;s.base_threshold=base_threshold_;s.last_update=last_update_;s.refractory_until=refractory_until_;s.adaptation=adaptation_;s.last_spike=last_spike_;s.spike_count=spike_count_;s.source=source_;s.target=target_;s.weight=weight_;s.delay=delay_;s.polarity=polarity_;s.telemetry=telemetry_;auto q=queue_;while(!q.empty()){s.pending.push_back(q.top());q.pop();}return s;}
void NeurodynamicSubstrate::restore(const NeuroSnapshot&s){if(!std::isfinite(s.now)||s.potential.size()!=s.base_threshold.size()||s.potential.size()!=s.last_update.size()||s.potential.size()!=s.refractory_until.size()||s.potential.size()!=s.adaptation.size()||s.potential.size()!=s.last_spike.size()||s.potential.size()!=s.spike_count.size()||s.source.size()!=s.target.size()||s.source.size()!=s.weight.size()||s.source.size()!=s.delay.size()||s.source.size()!=s.polarity.size())throw std::invalid_argument("invalid neuro snapshot");now_=s.now;next_sequence_=s.next_sequence;potential_=s.potential;base_threshold_=s.base_threshold;last_update_=s.last_update;refractory_until_=s.refractory_until;adaptation_=s.adaptation;last_spike_=s.last_spike;spike_count_=s.spike_count;source_=s.source;target_=s.target;weight_=s.weight;delay_=s.delay;polarity_=s.polarity;telemetry_=s.telemetry;outgoing_.assign(potential_.size(),{});while(!queue_.empty())queue_.pop();for(std::uint32_t i=0;i<source_.size();++i){if(source_[i]>=potential_.size()||target_[i]>=potential_.size()||weight_[i]<0||delay_[i]<=0)throw std::invalid_argument("invalid snapshot rho");outgoing_[source_[i]].push_back(i);}for(auto const&e:s.pending){if(e.target>=potential_.size()||!std::isfinite(e.time)||e.time<now_||!std::isfinite(e.amplitude))throw std::invalid_argument("invalid snapshot event");queue_.push(e);}}
}
