#include "se/relation_store.hpp"
#include <stdexcept>
namespace se {
void RelationStore::make_provisional(RelationHandle h){
 auto*e=get(h);if(!e||e->status==RelationStatus::Provisional)return;
 auto p=consolidated_[e->payload];e->payload=(std::uint32_t)provisional_.size();
 provisional_.push_back({p.support,p.lift,p.contradiction,p.usefulness,p.confirmations,p.last_evidence_world_tick});e->status=RelationStatus::Provisional;--consolidated_live_;++provisional_live_;
}
std::pair<Edge&,RelationHandle> RelationStore::connect(std::uint32_t source,std::uint32_t target,RelationType type,std::uint32_t action){Edge*found=nullptr;RelationHandle old{};for_each(source,[&](Edge&e,RelationHandle h){if(e.target==target&&e.type==type&&e.action==action){found=&e;old=h;}});if(found)return{*found,old};std::uint32_t id;if(!free_.empty()){id=free_.back();free_.pop_back();}else{id=allocated_++;if(id/page_size==pages_.size())pages_.emplace_back();}auto&s=slot(id);auto generation=s.edge.generation?s.edge.generation:1;auto payload=(std::uint32_t)provisional_.size();provisional_.emplace_back();s.source=source;s.next=no_slot;s.edge=Edge{target,.2,.3,0,type,action,RelationStatus::Provisional,payload,generation,0,true};if(heads_[source]==no_slot)heads_[source]=id;else slot(tails_[source]).next=id;tails_[source]=id;++live_;++provisional_live_;return{s.edge,handle(id,generation)};}
bool RelationStore::valid(RelationHandle h)const{auto id=index(h);return id<allocated_&&slot(id).edge.alive&&slot(id).edge.generation==h.generation;}
Edge*RelationStore::get(RelationHandle h){return valid(h)?&slot(index(h)).edge:nullptr;}const Edge*RelationStore::get(RelationHandle h)const{return valid(h)?&slot(index(h)).edge:nullptr;}
bool RelationStore::erase(RelationHandle h){if(!valid(h))return false;auto id=index(h);auto&s=slot(id);auto source=s.source,cur=heads_[source],previous=no_slot;while(cur!=no_slot&&cur!=id){previous=cur;cur=slot(cur).next;}if(cur==no_slot)return false;if(previous==no_slot)heads_[source]=s.next;else slot(previous).next=s.next;if(tails_[source]==id)tails_[source]=previous;if(s.edge.status==RelationStatus::Provisional)--provisional_live_;else --consolidated_live_;s.edge.alive=false;++s.edge.generation;s.next=no_slot;free_.push_back(id);--live_;return true;}
void RelationStore::consolidate(RelationHandle h){auto*edge=get(h);if(!edge||edge->status==RelationStatus::Consolidated)return;auto&p=provisional_[edge->payload];edge->payload=(std::uint32_t)consolidated_.size();consolidated_.push_back({p.support,p.confirmations,p.contradiction,p.usefulness,p.lift,p.last_evidence_world_tick});edge->status=RelationStatus::Consolidated;--provisional_live_;++consolidated_live_;}
std::size_t RelationStore::reserved_bytes()const{return heads_.capacity()*sizeof(std::uint32_t)+tails_.capacity()*sizeof(std::uint32_t)+free_.capacity()*sizeof(std::uint32_t)+pages_.capacity()*sizeof(Page)+provisional_.capacity()*sizeof(ProvisionalData)+consolidated_.capacity()*sizeof(ConsolidatedData);}
std::size_t RelationStore::logical_bytes()const{return heads_.size()*sizeof(std::uint32_t)+tails_.size()*sizeof(std::uint32_t)+free_.size()*sizeof(std::uint32_t)+pages_.size()*sizeof(Page)+provisional_.size()*sizeof(ProvisionalData)+consolidated_.size()*sizeof(ConsolidatedData);}
std::vector<PersistedRelation> RelationStore::snapshot()const{std::vector<PersistedRelation>out;out.reserve(live_);for(std::uint32_t source=0;source<heads_.size();++source)for_each(source,[&](const Edge&e,RelationHandle){PersistedRelation r;r.source=source;r.target=e.target;r.strength=e.strength;r.confidence=e.confidence;r.prediction=e.prediction;r.type=(std::uint8_t)e.type;r.action=e.action;r.status=(std::uint8_t)e.status;r.last_used_cognitive_tick=e.last_used_cognitive_tick;if(e.status==RelationStatus::Provisional){auto&p=provisional_[e.payload];r.support=p.support;r.confirmations=p.confirmations;r.lift=p.lift;r.contradiction=p.contradiction;r.usefulness=p.usefulness;r.last_evidence_world_tick=p.last_evidence_world_tick;}else{auto&p=consolidated_[e.payload];r.support=p.support;r.confirmations=p.confirmations;r.lift=p.lift;r.contradiction=p.contradiction;r.usefulness=p.usefulness;r.last_evidence_world_tick=p.last_evidence_world_tick;}out.push_back(r);});return out;}
std::vector<RelationHandle> RelationStore::handles()const{std::vector<RelationHandle>out;out.reserve(live_);for(std::uint32_t source=0;source<heads_.size();++source)for_each(source,[&](const Edge&,RelationHandle h){out.push_back(h);});return out;}
PersistedRelation RelationStore::state(std::uint32_t source,RelationHandle h)const{auto*e=get(h);if(!e)throw std::runtime_error("stale relation handle");PersistedRelation r;r.source=source;r.target=e->target;r.strength=e->strength;r.confidence=e->confidence;r.prediction=e->prediction;r.type=(std::uint8_t)e->type;r.action=e->action;r.status=(std::uint8_t)e->status;r.last_used_cognitive_tick=e->last_used_cognitive_tick;if(e->status==RelationStatus::Provisional){auto&p=provisional_[e->payload];r.support=p.support;r.confirmations=p.confirmations;r.lift=p.lift;r.contradiction=p.contradiction;r.usefulness=p.usefulness;r.last_evidence_world_tick=p.last_evidence_world_tick;}else{auto&p=consolidated_[e->payload];r.support=p.support;r.confirmations=p.confirmations;r.lift=p.lift;r.contradiction=p.contradiction;r.usefulness=p.usefulness;r.last_evidence_world_tick=p.last_evidence_world_tick;}return r;}
void RelationStore::update(RelationHandle h,const PersistedRelation&r){auto*e=get(h);if(!e)throw std::runtime_error("stale relation handle");e->strength=r.strength;e->confidence=r.confidence;e->prediction=r.prediction;e->last_used_cognitive_tick=r.last_used_cognitive_tick;if(e->status==RelationStatus::Provisional){auto&p=provisional_[e->payload];p.support=r.support;p.confirmations=r.confirmations;p.lift=r.lift;p.contradiction=r.contradiction;p.usefulness=r.usefulness;p.last_evidence_world_tick=r.last_evidence_world_tick;if((RelationStatus)r.status==RelationStatus::Consolidated)consolidate(h);}else{auto&p=consolidated_[e->payload];p.support=r.support;p.confirmations=r.confirmations;p.lift=r.lift;p.contradiction=r.contradiction;p.usefulness=r.usefulness;p.last_evidence_world_tick=r.last_evidence_world_tick;}}
void RelationStore::restore(std::size_t node_count,const std::vector<PersistedRelation>&rows){heads_.clear();tails_.clear();free_.clear();pages_.clear();provisional_.clear();consolidated_.clear();allocated_=0;live_=provisional_live_=consolidated_live_=0;resize_nodes(node_count);for(auto&r:rows){if(r.source>=node_count||r.target>=node_count)throw std::runtime_error("relation endpoint out of bounds");auto[e,h]=connect(r.source,r.target,(RelationType)r.type,r.action);e.strength=r.strength;e.confidence=r.confidence;e.prediction=r.prediction;e.last_used_cognitive_tick=r.last_used_cognitive_tick;auto&p=provisional(e);p.support=r.support;p.confirmations=r.confirmations;p.lift=r.lift;p.contradiction=r.contradiction;p.usefulness=r.usefulness;p.last_evidence_world_tick=r.last_evidence_world_tick;if((RelationStatus)r.status==RelationStatus::Consolidated)consolidate(h);}}
}
